version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persons
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./backend:/service

volumes:
  db-data:

networks:
  backend: